### ISSUE TITLE
Change efficiency calculation to remove FROM

### ISSUE THREAD

**Issue by ChrisCinelli** [wagoodman/dive#111]
It looks like that the FROM layer is part of the efficiency calculation score.
I suggest to remove it or at least, be able to toggle it off.
You may have a pretty big initial layers that dilutes a lot the other files changed down in the other layers. The same FROM layers may also have inefficiency that add up to the layers you actually have control over.

**Comment by wagoodman** [comment]
I see your point with indicating efficiency with only the layers you have control over. However, in some cases the user may have control over the base image and this would be useful to know (so ignoring the FROM layer by default would be undesirable). Making this configurable is tempting, but the efficiency score is supposed to be a fairly well-anchored metric. If this were to change, it would be non-obvious what value should be recommended... e.g. my base image is 500MB and I add 200MB, should I include the FROM layer in the analysis or not? *The list of inefficient files and size of wasted space output should be more valuable to the user than the score itself.* The score is more of an indicator saying "hey, you can do a bit better". 

But I see that "how much better" is in question... that is, diluting the score with a large base image can be a problem. However, if you don't include the base image in the score it's possible for someone to duplicate all duplicate all base image files and still have a great efficiency score, which I feel is bad (e.g. 10 MB base image, 10MB in changes, which dive today identifies 10MB of inefficient files but would identify 0MB of inefficient files if you ignore the FROM line). 

The flaw with the efficiency score in general is that it is based on percentage. If I have a 5MB base image, add 20MB to it, and dive detects 10 MB of inefficiency, then my image efficiency score is 60%. Say I rebuild the image (terribly) and I have a 500MB base image, add 200MB to it, and dive detects 100MB of inefficiency, then my image efficiency is still 60%. However, if you had to choose between using image A and image B you'd definitely pick A since it's much smaller over all (even though they have the same efficiency score). The same problem would be there if I ignore the FROM layer: both A and B would have an efficiency of 50%.

I agree with your statement that you can dilute the score with a large base image, but I feel that the score should remain an absolute measure of the entire image. The "wasted space" metric should also jump out to the user (e.g. "my efficiency is 50%, but I have only 100KB of wasted space, so I'm actually ok").

**Comment by wagoodman** [comment]
A notable exception is when this is being used for automated analysis instead of a user taking a look at the UI, in which case I've added a similar metric that does not include the base image (`highestUserWastedPercent` in #143 ). I'll probably have this added to the UI as well in an upcoming release.
