### ISSUE TITLE
Files in the FROM layer are shown as "unmodified" instead of "added"

### ISSUE THREAD

**Issue by ChrisCinelli** [wagoodman/dive#112]
When the FROM layer is selected, the files in that folder should not be consider "unchanged" but "added".
 Currently when unmodified files is toggled, the FROM layer does not show any files.

**Comment by wagoodman** [comment]
This is by design. If the user wants to see all added files in an image, then they can aggregate changes (^A) and unselect modified/removed/unchanged (^U, ^M, ^R) and get a list of files the user added. Though this is a semantic difference in behavior in other layers, I feel that it's the right choice.
