### ISSUE TITLE
apparent mismatched dependencies on 'go get'

### ISSUE THREAD

**Issue by oohook** [wagoodman/dive#147]
https://github.com/wagoodman/dive/blob/54979ae1ebaab7207f2fe6bd65e07266bd54dd76/image/docker_image.go#L7
——————————————————————
hello this code can`t import, I can`t saw it in https://github.com/docker , maybe the owner rename it into https://github.com/docker/go-docker ?

**Comment by wagoodman** [comment]
github redirects `github.com/docker/docker` to `github.com/moby/moby`, which is where the client code is hosted. Are you running `go build` with at least go 1.11 or greater?

**Comment by Azaradel** [comment]
I have similar issue when I try running `go get` command. Output from the cmd:
```
go: downloading github.com/docker/docker v0.0.0-20181126153310-0b7cb16dde4a20d024c7be59801d63bcfd18611b
go: verifying github.com/docker/docker@v0.0.0-20181126153310-0b7cb16dde4a20d024c7be59801d63bcfd18611b: checksum mismatch
        downloaded: h1:C23qRhx3B3aMAtWOn2mLj0pWiapqJmZyzoHRpTLpcHk=
        go.sum:     h1:T6w2S9UvmzJQBKIUsOs3+lNWfZea5yUPLh2eMihRrKY=
```
Removing related with this package entries in `go.sum` file does the job, but it is weird that it has different checksum.

**Comment by wagoodman** [comment]
What version of go are you using?

**Comment by Azaradel** [comment]
go1.11.4 darwin/amd64

**Comment by wagoodman** [comment]
I haven't been able to reproduce this, even when starting anew with a cleared cache or upgrading go. Are you still seeing this?

**Comment by luhring** [comment]
I've done some testing, and I've been able to reproduce the `checksum mismatch` error by reverting to an older version of Go. As noted in #137, Go was calculating go.sum hashes incorrectly prior to Go 1.11.4.

I was experiencing this issue, too, and then I noticed that I was running Go 1.11.2.

In order to have a clean, reproducible experiment, I started testing inside of **_Docker containers_** that I disposed of after each experiment. This rules out any state from my local development setup having an effect on the outcome of whether or not I could reproduce the `checksum mismatch` error.

### Reproducing the error

Here's a Dockerfile that allows the experiments to be repeated cleanly, allowing you to choose which Go version you use during a test run.

```Dockerfile
FROM ubuntu

WORKDIR /tmp

ENV GOPATH="/tmp/gopath"
RUN mkdir -p $GOPATH
ENV GOROOT="/usr/local/go"

RUN apt-get update && apt-get upgrade -y && apt-get install -y git wget gcc
RUN git clone https://github.com/wagoodman/dive.git

ARG GO_VERSION="1.11.4"
ENV GO_ARCHIVE="go$GO_VERSION.linux-amd64.tar.gz"

RUN wget https://dl.google.com/go/$GO_ARCHIVE
RUN tar -xvf $GO_ARCHIVE
RUN mv go /usr/local
ENV PATH="$GOPATH/bin:$GOROOT/bin:$PATH"

WORKDIR /tmp/dive

CMD go build
```

If you build this Docker image, you can specify the version of Go as a `--build-arg`. Then, when you run the container, you can see whether or not you receive the `checksum mismatch` error.

Here's how my testing went:

| Go version | Result |
| --- | --- |
| 1.11.2 (my version) | reproduced error |
| 1.11.3 (last version with go.sum bug) | reproduced error |
| 1.11.4 (first version without go.sum bug) | no error |
| 1.12.4 (current version) | no error |

#### Examples

To reproduce error:

```shell
$ docker build -t "dive-test" --build-arg GO_VERSION="1.11.3" .
$ docker run --rm dive-test
...
go: verifying github.com/docker/docker@v0.0.0-20181126153310-0b7cb16dde4a20d024c7be59801d63bcfd18611b: checksum mismatch
        downloaded: h1:C23qRhx3B3aMAtWOn2mLj0pWiapqJmZyzoHRpTLpcHk=
        go.sum:     h1:T6w2S9UvmzJQBKIUsOs3+lNWfZea5yUPLh2eMihRrKY=
```

To run without error:

```shell
$ docker build -t "dive-test" --build-arg GO_VERSION="1.11.4" .
$ docker run --rm dive-test
...
# no error!
```

**Comment by luhring** [comment]
**Note:** This may not recreate the same scenario in which the other folks saw the `checksum mismatch` error. They could've seen the same error but for a different reason — and I noticed that @Azaradel said they were using 1.11.4 already.

If that's the case, then I'd say the Dockerized testing environment still accomplishes two things:

1. It proves that the way to get the "wrong" hash value (`C23qRhx...`) is to use Go's code that was present prior to version 1.11.4. It seems extremely improbable that there's a _different_ hashing process and/or set of hash inputs that results in the exact same hash value.
1. It provides a means by which one could test out building Dive in a clean environment and perform other kinds of experiments than merely trying various versions of Go. For example, another set of tests could be run that attempt to build a dependency cache with _one_ version of Go and then build Dive with _another_ version of Go.

Anyway... hope this helps! 😃

**Comment by wagoodman** [comment]
Thanks @luhring for finding a concrete answer here... @Azaradel , @oohook , if you're still in this predicament update go to at least 1.11.4 or greater and clear the module cache created by older versions of go (`go clean -cache -modcache -i -r`).
