### ISSUE TITLE
Significant CPU Utilization, even when UI is idle

### ISSUE THREAD

**Issue by TJM** [wagoodman/dive#184]
I expect some CPU utilization while the image is being processed, but once the UI is open, I would think it would be fairly quiet. However, I have noticed that the CPU utilization is actually quite high (100-200%) on dive 0.7.0, OSX 10.12.6 with Docker Desktop Community v 2.0.0.3.

I just noticed my CPU fans were wailing in a "quiet" room, and found it was quite high in htop. If you let me know what to try, to get some more information, I can.

Tommy

**Comment by wagoodman** [comment]
@TJM great catch, thanks for reporting! The problem was an infinite loop between a layout change and the render function for the filetree ...and apparently my laptop is beefy enough where an infinite loop is still responsive and doesn't trigger the CPU fan :) . I've patched this in v0.7.1 (just released now).

**Comment by TJM** [comment]
Very interesting, I honestly wondered if it had anything to do with resizing the window. I was on battery in a quiet room, and have had "issues" with run away vagrant VMs (but that is usually after hibernation), so I am always listening for the fan. Thanks for fixing so quickly!

Tommy
