### ISSUE TITLE
TE VAN A DEJAR EL CULO COMO LA BANDERA DE JAPÓN

### ISSUE THREAD

**Issue by secu77** [wagoodman/dive#189]
Be carefull with:

```
Building on Macbook

docker run --rm -it \
      -v /usr/local/bin/docker:/bin/docker \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v  "$(pwd)":"$(pwd)" \
      -w "$(pwd)" \
      -v "$HOME/.dive.yaml":"$HOME/.dive.yaml" \
      wagoodman/dive:latest build -t <some-tag> .
```

https://medium.com/@kenzanmedia/hacking-docker-discovering-containers-6086761bc563

**Comment by wagoodman** [comment]
Indeed, mounting in the docker socket can be a security risk. This isn't something that I will address here with dive since a) it is up to the user to determine if running this is an acceptable risk relative to their needs, and b) there are other packaging options for linux and mac (however, they still require access to the daemon).
