### ISSUE TITLE
Support reading image from file

### ISSUE THREAD

**Issue by jpds** [wagoodman/dive#194]
My CI system lets me pre-fetch the Docker image and save it to a location on the filesystem for a CI job - I'd like to use this with dive so that my other image analysis jobs are consistent and also avoid using the Docker socket (which the CI system forbids).

However, when I try and give the file to the job, it fails with:

```
Image not available locally. Trying to pull 'docker/image'...
```

**Comment by wagoodman** [comment]
Actually, since dive needs individual layers it is already exporting the image from the daemon into a tar (via the `docker save` cmd). Dive can be (seemingly easily) modified to short circuit this process by providing the tar file directly from the user. This would also mean faster processing of the image for folks like you that already have the tar available.

@jpds Is your CI providing you a tar that resulted from a `docker save` command? or from another process/command that extracts the image filesystem.

**Comment by wagoodman** [comment]
Try out dive 0.9.1, with the `--source` option as `docker-archive`.
