### ISSUE TITLE
How do I donate to this project?

### ISSUE THREAD

**Issue by kilianc** [wagoodman/dive#251]
It just saved me 2h of work.

**Comment by wagoodman** [comment]
Always great to hear that dive saved folks time! What specifically did it help you with? Trimming the size down? Or trying to find out the source of an image build failure?

Coincidentally, I signed up for GitHub Sponsors a few days ago since it just got out of beta, it's still in the approval process... I added a badge in the readme for accepting donations via paypal @ https://www.paypal.me/wagoodman (Thanks!!).

**Comment by kilianc** [comment]
I had a bug in my image and the size was 5x what it was supposed to be. Turns out I had a misspelled line in my `. dockerignore` file.

Thanks!

**Comment by kilianc** [comment]
Saved me another hour today again :D <3
