### ISSUE TITLE
Why are all releases "pre-release"?

### ISSUE THREAD

**Issue by DannyBen** [wagoodman/dive#262]
This is the only repository I have seen that does not have a "latest" release.

The lack of `latest` release makes it harder to install the latest version programmatically.

In the majority of other repos that provide a release binary, I can do:

```
$ curl -s https://api.github.com/repos/wagoodman/dive/releases/latest
```

or more specifically (in my bash scripts):

```bash
# Get the latest version
version=$(curl -s https://api.github.com/repos/wagoodman/dive/releases/latest | grep "tag_name" | cut -d : -f 2,3 | tr -d \"\ ,v)
```

but this trick does not work if there is no latest release...

**Comment by wagoodman** [comment]
This is to denote that this is a pre-1.0 release, however, I overlooked that the `latest` URL would not be available when releasing with the pre-release flag. I think this is useful enough to stop using the pre-release flag before 1.0.

**Comment by eine** [comment]
@wagoodman, I think that your interpretation of "pre-release" is different from the most widespread usage of the term in the context of semantic versioning. According to the naming, all the releases that you published so far are proper releases. The fact that those are "pre-1.0" versions/releases is known because all of them start with `0.`. Type "pre-release" should be used for versions such as `v0.0.0-rc`.

Hence, you may use "pre-releases" say a week before "releases", so that users that programmatically retrieve the latest version can test/evaluate it. Other users that retrieve the latest "stable" will not be affected. However, I don't know if the naming of docker images (goreleaser) would need to be fixed to support this.

**Comment by wagoodman** [comment]
Thanks for your input, I've made the last available release not a pre-release and removed the prerelease flag from the go releaser config. `curl` away! :)

**Comment by DannyBen** [comment]
Thank you.
