### ISSUE TITLE
Graduate to central homebrew repository

### ISSUE THREAD

**Issue by ahmetb** [wagoodman/dive#97]
Since you have almost 9k stars, you are eligible to submit your formula to https://github.com/Homebrew/homebrew-core/blob/master/Formula/ instead of maintaining your own tap.

**Comment by asmaaswt** [comment]
Good for now

**Comment by wagoodman** [comment]
Thanks for the suggestion, @ahmetb. Since homebrew-core formulas shouldn't be binaries (https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md) I'll probably submit a cask instead (https://github.com/Homebrew/homebrew-cask). It also seems odd to have users recompile what is a static binary already on the github releases page --especially since there are build flags for setting the version and build time (https://github.com/wagoodman/dive/blob/master/.goreleaser.yml#L12).

**Comment by ahmetb** [comment]
A lot of projects similar to this distribute via Homebrew. It's not odd to recompile what's on GitHub releases page. Homebrew community believes in builds coming from a specific rev, built on their machines and distributed via bintray for security.

You can easily write a brew formula that still stamps the binary with the correct version, but it will have a different build time. I recommend grepping "ldflags" in homebrew-core/Formulas directory and you'll see plenty of examples.

If anything, you can define the build block to run a makefile or a build script of your choice. 

P.S. stamping build times is bad for reproducibility, and they're rarely of any use. I don't recommend.

**Comment by wagoodman** [comment]
Thanks to @chenrui333 on #213 this has been completed!
